/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app-tabs`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app-tabs.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/animated-icon`; params?: Router.UnknownInputParams; } | { pathname: `/../components/animated-icon.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-text`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/db-react-logic`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/admin_panel_styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/app-tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/app-tabs.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/animated-icon`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/animated-icon.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/themed-text`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/db/db-react-logic`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/db/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/database`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/db/admin_panel_styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/../components/app-tabs${`?${string}` | `#${string}` | ''}` | `/../components/app-tabs.web${`?${string}` | `#${string}` | ''}` | `/../components/animated-icon${`?${string}` | `#${string}` | ''}` | `/../components/animated-icon.web${`?${string}` | `#${string}` | ''}` | `/../components/external-link${`?${string}` | `#${string}` | ''}` | `/../components/themed-text${`?${string}` | `#${string}` | ''}` | `/../components/themed-view${`?${string}` | `#${string}` | ''}` | `/../components/db/db-react-logic${`?${string}` | `#${string}` | ''}` | `/../components/db/supabase${`?${string}` | `#${string}` | ''}` | `/database${`?${string}` | `#${string}` | ''}` | `/../components/db/admin_panel_styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app-tabs`; params?: Router.UnknownInputParams; } | { pathname: `/../components/app-tabs.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/animated-icon`; params?: Router.UnknownInputParams; } | { pathname: `/../components/animated-icon.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/external-link`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-text`; params?: Router.UnknownInputParams; } | { pathname: `/../components/themed-view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/db-react-logic`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/admin_panel_styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
