/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/admin_panel_styles`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MapComponent.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/db-react-logic`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/database`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MapComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/db/admin_panel_styles`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MapComponent.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/db/db-react-logic`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/db/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/database${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../components/MapComponent${`?${string}` | `#${string}` | ''}` | `/../components/db/admin_panel_styles${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/../components/MapComponent.web${`?${string}` | `#${string}` | ''}` | `/../components/db/db-react-logic${`?${string}` | `#${string}` | ''}` | `/../components/db/supabase${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/admin_panel_styles`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MapComponent.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/db-react-logic`; params?: Router.UnknownInputParams; } | { pathname: `/../components/db/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
